### ISSUE TITLE
Language Support: Rust

### ISSUE THREAD

**Issue by RomainMuller** [aws/jsii#1684]
|PR|Champion|
|--|--------|
|# |        |

## Description

- [ ] Rust as a target language (collaboration with JetBrains)

## Progress

- [x] Tracking Issue Created
- [ ] RFC PR Created 
- [ ] Core Team Member Assigned 
- [ ] Initial Approval / Final Comment Period
- [ ] Ready For Implementation
    
    - [ ] implementation issue 1
- [ ] Resolved

**Comment by opensource-inemar-net** [comment]
Hi !
Rust doesn't support inheritance and overriding methods. 

Implementing a usable workaround for this would be quite complicated and according to all the AWS CDK examples I have seen the only use of inheritance is done when setting up an  App or Stack. And this seems to be more by convention and not due to any real advantage.

Can you please provide some guidance on the subject.

thanks & regards Oliver

**Comment by RomainMuller** [comment]
@opensource-inemar-net this is definitely a challenge for supporting Rust. There are similar problems with Golang. We are looking into options at this point and haven't quite homed in on any particular candidate solution just yet.

**Comment by opensource-inemar-net** [comment]
If there is no further input I would proceed on the following assumption:
- inheritance is not really needed - if really needed it can be done. all functions are moved to TRAITs there it is possible to construct own extended objects if really needed
- overriding of functions won't be provided in phase 1. In a second phase a generic mechanism shall be provided which allows to provide a function/closure which would be called with the JSON input/output of JSII and which would allow overriding is absolutely needed.

After I am able to generate some working rust code. I will try to write a PRC and attach it here.

Thanks for the input

**Comment by RomainMuller** [comment]
> inheritance is not really needed 

I mean. If you look at CDK users, extending `Construct` or `Stack` is an _extremely_ common thing to do...

**Comment by opensource-inemar-net** [comment]
I think extending Stack is only done, because it is in the examples. (In my AWS CDK Java I also extend Stack to create the infrastructure).
In rust you write a function to build your Stack with exactly the same result. 

I think only constructor is overwritten to create all the included parts. It is more a convention.

This will cause problems with Rosetta automatic example creation. But I don't know how good this works in reality.

**Comment by RomainMuller** [comment]
> This will cause problems with Rosetta automatic example creation. But I don't know how good this works in reality.

I mean, it works as good as we make it... 😅

**Comment by michaetto** [comment]
Rust is the perfect choice for IaC for many reasons. To mention just two for its powerful typing system and some of the best developer support from the language compiler for correctness. Make it happen please, please, please :).

**Comment by yuriy-yarosh** [comment]
Whole JSII should be ported to Rust or golang itself...

I'm really tired setting my Node flags to `--optimize-for-size --gc-interval=500` with `--max-semi-space-size=512 --max-old-space-size=1536` just to make it work on 32Gb mem rig, with CDKTF.

Rust or golang would've been much faster and efficient choice.

**Comment by LoganDark** [comment]
> Whole JSII should be ported to Rust or golang itself...
> 
> I'm really tired setting my Node flags to `--optimize-for-size --gc-interval=500` with `--max-semi-space-size=512 --max-old-space-size=1536` just to make it work on 32Gb mem rig, with CDKTF.
> 
> Rust or golang would've been much faster and efficient choice.

pleaase don't bump years-old issues just to ask for what is already in the title, thanks~

**Comment by yuriy-yarosh** [comment]
@LoganDark as for me the whole existence of JSII in TS is highly controversial - JSII bundles can weight up to gigabytes and calling JSII node runtime out of rust, or any other lang, makes no perf difference whatsoever... so I don't really get myriads of langs support for CDK's, if performance and overall Development Experience is somewhere between non-existent and mediocre.
