### ISSUE TITLE
GoLang Runtime Library

### ISSUE THREAD

**Issue by MrArnoldPalmer** [aws/jsii#1822]
### Proposed Solution
Create a private npm module named `@jsii/go-runtime` with a Go module that will be a dependency of all generated JSII Go modules. This module will use `os/exec` to create a child process running node and the jsii-runtime and handle communication between it and the generated host modules.

See [Host Library](https://github.com/aws/jsii/blob/master/docs/handbooks/language-implementation.md#host-library) in the language implementation handbook for details.

- [x] https://github.com/aws/jsii/issues/2039 Object creation
- [x] https://github.com/aws/jsii/issues/2047 JSII to native value casting
- [x] https://github.com/aws/jsii/issues/2127 Go runtime method invocation
- [x] https://github.com/aws/jsii/issues/2128 Go runtime get/set implementation

***Unresolved Questions***
Since go modules are just source files published to a git repository, can we just use this repo with our existing tagging system? Is a `go.mod` able to point to the runtime modules specific location?

**Comment by SoManyHs** [comment]
Related: https://github.com/aws/jsii/pull/1894
