### ISSUE TITLE
Go Build Tooling & Documentation

### ISSUE THREAD

**Issue by MrArnoldPalmer** [aws/jsii#1824]
### Tasks

- [ ] Integrate GoLang documentation generation tooling with code generation and packaging - https://github.com/aws/jsii/issues/2438
- [ ] Add support for snippet translation in `jsii-rosetta` - https://github.com/aws/jsii/issues/2439
- [ ] JSII Publish GH Action Support - https://github.com/aws/jsii/issues/2440
- [ ] Go Compliance Test Suite - https://github.com/aws/jsii/issues/2441
