### ISSUE TITLE
Go Client Library Testing and Verification

### ISSUE THREAD

**Issue by MrArnoldPalmer** [aws/jsii#2445]
Testing and Verification against aws-cdk and cdk8s

- [ ] Create Repository for cdk8s-go - https://github.com/aws/jsii/issues/2443
- [ ] Integrate Go Code Generation into cdk8s build - https://github.com/aws/jsii/issues/2444
- [ ] Create Repository for aws-cdk-go
- [ ] Integrate Go Code Generation into aws-cdk build - https://github.com/aws/jsii/issues/1834
- [ ] Add GoDoc site generation to aws-cdk reference documentation
