### ISSUE TITLE
jsii-reflect: useful capabilities from deCDK

### ISSUE THREAD

**Issue by eladb** [aws/jsii#367]
List of capabilities we could extract from our work on [deCDK]:

- [ ] Load a directory full of jsii files into a TypeSystem
- [ ] Load a set of node modules by name into a TypeSystem (requires that they are defined as dependencies of the current model) - replaces [this](https://github.com/awslabs/aws-cdk/blob/cec8564a3c17b0dddd1f274848a4698985328bc0/tools/decdk/lib/util.ts#L15)
- [x] [`Type.isDataType`](https://github.com/awslabs/aws-cdk/blob/cec8564a3c17b0dddd1f274848a4698985328bc0/tools/decdk/lib/jsii2schema.ts#L432)
- [x] [`Type.isEnum`](https://github.com/awslabs/aws-cdk/blob/cec8564a3c17b0dddd1f274848a4698985328bc0/tools/decdk/lib/jsii2schema.ts#L511)
- [x] [`Type.extendsType`](https://github.com/awslabs/aws-cdk/blob/cec8564a3c17b0dddd1f274848a4698985328bc0/tools/decdk/lib/jsii2schema.ts#L535)
- [x] [`Type.allImplementations`](https://github.com/awslabs/aws-cdk/blob/cec8564a3c17b0dddd1f274848a4698985328bc0/tools/decdk/lib/jsii2schema.ts#L589)
- [ ] [`ClassType.allSubclasses`](https://github.com/awslabs/aws-cdk/blob/cec8564a3c17b0dddd1f274848a4698985328bc0/tools/decdk/lib/jsii2schema.ts#L601)

**Comment by RomainMuller** [comment]
I've done most of those in #366.

In my opinion:
- `ClassType.allSubclasses` is achieved by `Type.allImplementations`
- *Load a set of node modules by name into a `TypeSystem` (requires that they are defined as dependencies of the current model)* is achieved by `TypeSystem.loadModule`, but I haven't checked in-depth.
